/* REGISTRATION */
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_CITY = 'CHANGE_CITY';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_STATION = 'CHANGE_STATION';
export const CHANGE_PHONE = 'CHANGE_PHONE';
export const CHANGE_PASS = 'CHANGE_PASS';
export const CHANGE_CHECKBOX = 'CHANGE_CHECKBOX';
export const CHECK_FIELDS = 'CHECK_FIELDS';
export const SUCCESS_REGISTRATION = 'SUCCESS_REGISTRATION';
export const CLEAR_REG = 'CLEAR_REG';
export const SUBMIT = 'SUBMIT';

/* LOGIN */

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const SET_USER_SESSION = 'SET_USER_SESSION';
