const CHANGE_NAME = 'CHANGE_NAME';
const CHANGE_CITY = 'CHANGE_CITY';
const CHANGE_EMAIL = 'CHANGE_EMAIL';
const CHANGE_STATION = 'CHANGE_STATION';
const CHANGE_PHONE = 'CHANGE_PHONE';
const CHANGE_PASS = 'CHANGE_PASS';
const SUBMIT = 'SUBMIT';
export {
    CHANGE_NAME,CHANGE_CITY,CHANGE_EMAIL,CHANGE_PASS,CHANGE_PHONE,CHANGE_STATION,SUBMIT
}