/* REGISTRATION */
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_CITY = 'CHANGE_CITY';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_STATION = 'CHANGE_STATION';
export const CHANGE_PHONE = 'CHANGE_PHONE';
export const CHANGE_PASS = 'CHANGE_PASS';
export const CHANGE_CHECKBOX = 'CHANGE_CHECKBOX';
export const CHECK_FIELDS = 'CHECK_FIELDS';
export const SUCCESS_REGISTRATION = 'SUCCESS_REGISTRATION';
export const CLEAR_REG = 'CLEAR_REG';
export const SUBMIT = 'SUBMIT';

/* LOGIN */

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const SET_USER_SESSION = 'SET_USER_SESSION';
export const EXIT = 'EXIT';

/* USER */

export const LOAD_PROFILE = 'LOAD_PROFILE'; // для асинхронного вызова следующего экшна
export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';

/* REQUEST */

export const LOAD_USER_INFO = 'LOAD_USER_INFO';
export const SET_USER_INFO = 'SET_USER_INFO';
export const CHANGE_TYPE = 'CHANGE_TYPE';
export const CHANGE_MODEL = 'CHANGE_MODEL';
export const CHANGE_BRAND = 'CHANGE_BRAND';
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION';
export const CHANGE_EMAIL_NOTIFICATION = 'CHANGE_EMAIL_NOTIFICATION';
export const CHANGE_PHONE_NOTIFICATION = 'CHANGE_PHONE_NOTIFICATION';
export const ADD_REQUEST = 'ADD_REQUEST';
export const ADD_REQUEST_SUCCESS = 'ADD_REQUEST_SUCCESS';